import { useUser } from "@clerk/nextjs";
import { observer } from "mobx-react";
import { type NextPage } from "next";
import Head from "next/head";
import Card from "~/components/Card";
import NewBuilding from "~/components/NewBuilding";
import StaticModal from "~/components/StaticModal";
import { useStore } from "~/stores/building.store";
import { api } from "~/utils/api";

const Home: NextPage = observer(() => {
  const { buildingStore } = useStore();
  const { showModal, setShowModal } = buildingStore;
  const user = useUser();
  const buildingsList = api.building.getUserBuildingsList.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={()=>{setShowModal(true)}} type="button" className="text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-500 dark:focus:ring-blue-800">Add building</button>

      {showModal ? <StaticModal position={'top-1/4 left-1/2 translate-x--full'}>
        <NewBuilding />
      </StaticModal> : null}

      {user ? <ul className="flex flex-col gap-4">
        {buildingsList?.data?.map((building: any, index: number) => (
          <li key={index}>
            <Card content={building.name} buildingId={building.id} />
          </li>
        ))}
      </ul> : null}
    </>
  );
});

export default Home;
